### ISSUE TITLE
sortedlist 试两次

### ISSUE THREAD

**Issue by fulldecent** [buckyos/DCRM#6]
{ "hash": "0x39c767e230f1cc4d8fa7baa4ef8c39bc2e4add8680d09bfe086e1efdaa0d6437", "score": 290 }, // 10
    { "hash": "0x39c767e230f1cc4d8fa7baa4ef8c39bc2e4add8680d09bfe086e1efdaa0d6438", "score": 290 }, // 10

看那个先进

**Comment by weiqiushi** [comment]
According to  current implementation, two items with the same score are sorted in order of insertion, from first to last. If the inserted item has the same score as the last one in list, the insertion will be considered invalid.

**Comment by weiqiushi** [comment]
I updated the testcase to include insert two items which has same score. it will ranked by their insert order.
